- name: update
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
- name: tap
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew.taps }}'
- name: install packages
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    options: '{{ item.options | default(None) }}'
  with_items: '{{ homebrew.packages }}'
- name: install cask packages
  homebrew_cask:
    name: '{{ item.name }}'
    state: installed
    options: '{{ item.options | default(None) }}'
  environment:
    HOMEBREW_CASK_OPTS: '--appdir=/Applications'
  with_items: '{{ homebrew.cask_packages }}'
- name: install Ricty
  block:
    - name: get Ricty file list
      shell: ls $(brew --prefix ricty)/share/fonts/Ricty*.ttf
      register: ricty_files
      changed_when: false
    - name: install Ricty
      copy:
        src: '{{ item }}'
        dest: ~/Library/Fonts/
      with_items: "{{ ricty_files.stdout_lines }}"
      notify: run fc-cache
