- name: add homebrew cask opts
  lineinfile:
    dest: ~/.bash_profile
    line: 'export HOMEBREW_CASK_OPTS="--appdir=/Applications"'
    create: yes
- name: reload .bash_profile
  shell: source ~/.bash_profile executable=/bin/bash
  changed_when: false
- name: hombrew update
  homebrew:
    update_homebrew: yes
- name: homebrew tap
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew.taps }}'
- name: homebrew cask packages install
  homebrew_cask:
    name: '{{ item.name }}'
    state: installed
  environment:
    HOMEBREW_CASK_OPTS: '--appdir=/Applications'
  with_items: '{{ homebrew.cask_packages }}'
- name: homebrew packages install
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  with_items: '{{ homebrew.packages }}'
