- name: update
  homebrew:
    update_homebrew: yes
- name: tap
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew.taps }}'
- name: install packages
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    options: '{{ item.options | default(None) }}'
  with_items: '{{ homebrew.packages }}'
- name: add homebrew cask opts
  lineinfile:
    dest: ~/.bashrc
    line: 'export HOMEBREW_CASK_OPTS="--appdir=/Applications"'
    create: yes
- name: install cask packages
  homebrew_cask:
    name: '{{ item.name }}'
    state: installed
    options: '{{ item.options | default(None) }}'
  environment:
    HOMEBREW_CASK_OPTS: '--appdir=/Applications'
  with_items: '{{ homebrew.cask_packages }}'
- name: install Ricty
  block:
    - name: get Ricty ttf files
      shell: ls $(brew --prefix ricty)/share/fonts/Ricty*.ttf
      register: ricty_files
      changed_when: false
    - name: install Ricty
      copy:
        src: '{{ item }}'
        dest: ~/Library/Fonts/
      with_items: "{{ ricty_files.stdout_lines }}"
      notify: run fc-cache
- name: add completions
  blockinfile:
    dest: ~/.bashrc
    block: |
      [ -f $(brew --prefix)/etc/bash_completion ] && . $(brew --prefix)/etc/bash_completion
    marker: "# {mark} ANSIBLE MANAGED BLOCK completions"
    create: yes
- name: direnv
  blockinfile:
    dest: ~/.bashrc
    block: |
      export EDITOR=code
      eval "$(direnv hook bash)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK direnv"
    create: yes
- name: ghq
  blockinfile:
    dest: ~/.bashrc
    block: |
      alias g='cd $(ghq root)/$(ghq list | peco)'
      alias gh='hub browse $(ghq list | peco | cut -d "/" -f 2,3)'
      [ -e "${HOME}/bin/opt/ghq-init.bash" ] && source "${HOME}/bin/opt/ghq-init.bash"
    marker: "# {mark} ANSIBLE MANAGED BLOCK ghq"
    create: yes
- name: reload .bash_profile
  shell: source ~/.bash_profile executable=/bin/bash
  changed_when: false
