- name: install goenv
  homebrew:
    name: ['goenv']
- name: check latest version
  shell: sh -lc 'goenv install -l | grep -v - | tail -1 | tr -d " "'
  register: latest
  changed_when: false
- debug:
    msg: 'go latest version: {{ latest.stdout }}'
- include: version.yml version={{ item }}
  with_items: '{{ goenv.installs }}'
- name: set goenv global
  include: global.yml version={{ goenv.global }}
  when: goenv.global
