- name: install goenv
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: ~/.goenv
- name: rehash
  shell: bash -lc 'goenv rehash'
  changed_when: false
- name: check latest version
  shell: bash -lc 'goenv install -l | tr -d " " | grep -e "^[\.0-9]\+$" | tail -1'
  register: latest
  changed_when: false
- debug:
    msg: 'go latest version: {{ latest.stdout }}'
- include: version.yml version={{ item }}
  with_items: '{{ goenv.installs }}'
- name: set goenv global
  include: global.yml version={{ goenv.global }}
  when: goenv.global
