- name: install sdk package {{ item.name }}
  expect:
    command: './sdkmanager --verbose "{{ item.name }}"'
    chdir: '{{ android.sdk.dir }}/tools/bin/'
    timeout: 300
    responses:
      "Accept\\? \\(y/N\\): .*": "y"
  register: result
  changed_when: '"Install" in result.stdout'
