- name: update sdk
  expect:
    command: ./sdkmanager --update --verbose
    chdir: '{{ android.dir }}/android-sdk/tools/bin/'
    timeout: 300
    responses:
      "Accept\\? \\(y/N\\): .*": "y"
  register: result
  changed_when: '"Install" in result.stdout'
