- name: check rbenv global
  shell: sh -lc 'rbenv global'
  register: result
  changed_when: false
- name: rbenv global {{ version }}
  shell: sh -lc 'rbenv global "{% if rbenv.global == 'latest' %}{{ latest.stdout }}{% else %}{{ rbenv.global }}{% endif %}"'
  when: latest.stdout != result.stdout and rbenv.global != result.stdout
