- name: check rbenv global
  shell: sh -lc 'rbenv global'
  register: rbenv_global
  changed_when: false
- name: rbenv global {{ version }}
  shell: sh -lc 'rbenv global {{ version }}'
  when: version not in rbenv_global.stdout
