- name: check rbenv global
  shell: rbenv global
  register: rbenv_global
  changed_when: false
- name: rbenv global {{ version }}
  shell: rbenv global {{ version }}
  when: version not in rbenv_global.stdout
