- name: install rbenv
  homebrew:
    name: ['rbenv', 'ruby-build']
- include: version.yml
  with_items: '{{ rbenv.installs }}'
- name: set rbenv global
  include: global.yml version={{ rbenv.global }}
  when: rbenv.global
