- name: install ruby {{ version }}
  shell: bash -lc 'rbenv install -s "{% if version == 'latest' %}{{ latest.stdout }}{% else %}{{ version }}{% endif %}"'
  register: result
  changed_when: result.stdout != ""
