- name: create .pydistutils.cfg
  copy:
    src: roles/pip/files/.pydistutils.cfg
    dest: ~/
- name: upgrade pip
  shell: pip install --upgrade pip
  register: result
  changed_when: '"Requirement already up-to-date" not in result.stdout'
- name: install pips
  pip:
    name: '{{ item.name }} '
  with_items: '{{ pips }}'
