- name: git completion
  blockinfile:
    dest: ~/.bashrc
    block: |
      source /usr/local/etc/bash_completion.d/git-prompt.sh
      source /usr/local/etc/bash_completion.d/git-completion.bash

      GIT_PS1_SHOWDIRTYSTATE=true
      export PS1='\[\033[32m\]\h\[\033[00m\]:\[\033[36m\]\W\[\033[31m\]$(__git_ps1)\[\033[00m\]\\$ '
    marker: "# {mark} ANSIBLE MANAGED BLOCK git"
    create: yes
- name: reload .bash_profile
  shell: source ~/.bash_profile executable=/bin/bash
  changed_when: false
- name: set git configs
  git_config:
    name: '{{ item.name }}'
    scope: global
    value: '{{ item.value }}'
  with_items: '{{ git.configs }}'
